// Proxy Auto-Config file generated by autoproxy2pac, 2014-04-20 14:32:19
function FindProxyForURL(url, host) {
    var autoproxy = 'PROXY 127.0.0.1:8087';
    var blackhole = 'PROXY 127.0.0.1:8086';
    var defaultproxy = 'DIRECT';
    if (isPlainHostName(host) ||
        shExpMatch(host, 'localhost.*') ||
        host == '127.0.0.1') {
        return "DIRECT";
    } else if (FindProxyForURLByAdblock(url, host) != defaultproxy ||
               host == 'p.tanx.com' ||
               host == 'a.alimama.cn' ||
               host == 'pagead2.googlesyndication.com' ||
               dnsDomainIs(host, '.doubleclick.net')) {
        return blackhole;
    } else if (shExpMatch(host, '*.google*.*') ||
               dnsDomainIs(host, '.ggpht.com') ||
               dnsDomainIs(host, '.wikipedia.org') ||
               dnsDomainIs(host, '.sourceforge.net') ||
               dnsDomainIs(host, '.sf.net') ||
               host == 'sourceforge.net' ||
               host == 'cdnjs.cloudflare.com' ||
               host == 'wp.me' ||
               host == 'po.st' ||
               host == 'goo.gl') {
        return autoproxy;
    } else {
        return FindProxyForURLByAutoProxy(url, host);
    }
}

// AUTO-GENERATED RULES, DO NOT MODIFY!
var blackhole_host = {
    'jxad.jx163.com': 1,
    '91339.com': 1,
    'cyacc.com': 1,
    'log.hiiir.com': 1,
    'notice.uchome.manyou.com': 1,
    'shurumedia.com': 1,
    'ttmsg.qianqian.com': 1,
    'un.5d6d.com': 1,
    'uu456.com': 1,
    'xcy8.com': 1,
    'ashow.pcpop.com': 1,
    'go.hangzhou.com.cn': 1,
    'iads.xinmin.cn': 1,
    'log.daqi.com': 1,
    'sa.uusee.com': 1,
    'imghw.3gsc.com.cn': 1,
    'acsystem.wasu.cn': 1,
    'analytics.tv189.cn': 1,
    'edsystem.wasu.cn': 1,
    'pp.7060.com': 1,
    'ugcad.pps.tv': 1,
    'a-m-s.poco.cn': 1,
    'a4.yeshj.com': 1,
    'abc.hkepc.com': 1,
    'admd.yam.com': 1,
    'cdnlog.zhenai.com': 1,
    'data.xici.net': 1,
    'eap.enorth.com.cn': 1,
    'hudong.pl.youku.com': 1,
    'images.chinaz.com': 1,
    'life.e0575.com': 1,
    'link.fobshanghai.com': 1,
    'log.mtime.cn': 1,
    'p.fobshanghai.com': 1,
    'pic.2u.com.cn': 1,
    'stat.baike.com': 1,
    'sub.powerapple.com': 1,
    'tongji.500wan.com': 1,
    'xc.macd.cn': 1,
    'adgeo.163.com': 1,
    'img1.126.net': 1,
    'img2.126.net': 1,
    'popme.163.com': 1,
    'stat.ws.126.net': 1,
    'a.youdao.com': 1,
    'market.178.com': 1,
    'tuiguang.178.com': 1,
    'market.21cn.com': 1,
    'shows.21cn.com': 1,
    's.360.cn': 1,
    's.so.360.cn': 1,
    'tf.360.cn': 1,
    'stat.56.com': 1,
    'v-56.com': 1,
    'shrek.6.cn': 1,
    'am.6park.com': 1,
    'image.6park.com': 1,
    'stats.autohome.com.cn': 1,
    'cb.baidu.com': 1,
    'cbjs.baidu.com': 1,
    'cpro.baidu.com': 1,
    'cpro.baidustatic.com': 1,
    'drmcmm.baidu.com': 1,
    'duiwai.baidu.com': 1,
    'eiv.baidu.com': 1,
    'spcode.baidu.com': 1,
    'ubmcmm.baidustatic.com': 1,
    'msg.iqiyi.com': 1,
    'a.baomihua.com': 1,
    'a.pomoho.com': 1,
    'systemlog.pxtadmin.com': 1,
    'click.bokecc.com': 1,
    'imedia.bokecc.com': 1,
    'dvs.china.com': 1,
    'union.china.com.cn': 1,
    'sortweb.chinatimes.com': 1,
    'doubleclick.tv002.com': 1,
    'by.tel.cdndm.com': 1,
    'inte.sogou.com': 1,
    'market.duowan.com': 1,
    'same.eastmoney.com': 1,
    'count.enet.com.cn': 1,
    'ettoday.travelrich.com': 1,
    'msg.ettoday.net': 1,
    'pic.fengniao.com': 1,
    'adk.funshion.com': 1,
    'adm.funshion.com': 1,
    'vas.funshion.com': 1,
    'images.gxsky.com': 1,
    'images.nnsky.com': 1,
    'hxjs.tool.hexun.com': 1,
    'itv.hexun.com': 1,
    'hiad.myweb.hinet.net': 1,
    'p4u.hinet.net': 1,
    'p8u.hinet.net': 1,
    'g.hsw.cn': 1,
    'goto.www.iciba.com': 1,
    'de.deliver.ifeng.com': 1,
    '86file.megajoy.com': 1,
    'pcs1.app.joy.cn': 1,
    'vd.kankanews.com': 1,
    'panda.kdnet.net': 1,
    'super.cat898.com': 1,
    'super.kdnet.net': 1,
    'st.vq.ku6.cn': 1,
    'dc.letv.com': 1,
    'pro.hoye.letv.com': 1,
    'promotion.msn.com.tw': 1,
    'imgpub.mop.com': 1,
    'pub.mop.com': 1,
    'btm.pchome.net': 1,
    'btn.pchome.net': 1,
    'js-1.pchome.net': 1,
    'stat.pchome.net': 1,
    'acount.pconline.com.cn': 1,
    'error.pixplug.in': 1,
    'pixgold.com': 1,
    'referer.pixplug.in': 1,
    'banana.plurk.com': 1,
    'trex.plurk.com': 1,
    'de.as.pptv.com': 1,
    'synacast.com': 1,
    'web.data.pplive.com': 1,
    'att.rkanr.com': 1,
    'aa.sdo.com': 1,
    'aagw.sdo.com': 1,
    'adrs.sdo.com': 1,
    'ck.sdo.com': 1,
    'sy.sdo.com': 1,
    'wa.gtimg.com': 1,
    'tajs.qq.com': 1,
    'tcss.qq.com': 1,
    'gdt.qq.com': 1,
    'isdspeed.qq.com': 1,
    'up.hiao.com': 1,
    'ebp.renren.com': 1,
    'shaft.jebe.renren.com': 1,
    'log.interest.mix.sina.com.cn': 1,
    'rs.sinajs.cn': 1,
    'p4p.sina.com.cn': 1,
    'dcads.sina.com.cn': 1,
    'biz.weibo.com': 1,
    'as.sinahk.net': 1,
    'xls.go.sohu.com': 1,
    'z.t.sohu.com': 1,
    'vm.aty.sohu.com': 1,
    'brand.sogou.com': 1,
    'countpage.sznews.com': 1,
    'click.tianyaui.com': 1,
    'js.pub.tom.com': 1,
    'sc.tom.com': 1,
    'ff.wanlicity.com': 1,
    'adm.265g.com': 1,
    'event.udn.com': 1,
    'sp.vcimg.com': 1,
    'poster.weather.com.cn': 1,
    'aoodoo.feng.com': 1,
    'aoodoo.weiphone.com': 1,
    'd0.xcar.com.cn': 1,
    'd1.xcarimg.com': 1,
    'dw.xcar.com.cn': 1,
    'adm.xmfish.com': 1,
    'a.xizi.com': 1,
    'analytics-union.sandai.net': 1,
    'kkpgv2.xunlei.com': 1,
    'record.kuai.xunlei.com': 1,
    'fun.ynet.com': 1,
    'ranking.ynet.com': 1,
    'atm.youku.com': 1,
    'l.ykimg.com': 1,
    'v.stats.yytcdn.com': 1,
    'copy.ousns.com': 1,
    'yktj.yzz.cn': 1,
    'imp.zol.com.cn': 1,
    'p.zol-img.com.cn': 1,
    'gqgc.sz.zj.cn': 1,
    'log.zongheng.com': 1,
    'adpub.yaolan.com': 1,
    'apikozakanet-a.akamaihd.net': 1,
    'apiscantacknet-a.akamaihd.net': 1,
    'appnext-a.akamaihd.net': 1,
    'hdapp1003-a.akamaihd.net': 1,
    'hdapp1008-a.akamaihd.net': 1,
    'cnxad.net': 1,
    'd3otqu317bbc85.cloudfront.net': 1,
    'tg.1155t.cn': 1,
    '118.26.200.246': 1,
    '360safego.com': 1,
    '411pp.net': 1,
    '50.117.120.149': 1,
    '8jkx.com': 1,
    'a5.yeshj.com': 1,
    'a6.hujiang.com': 1,
    'abc1.sdo.com': 1,
    'ad.17173.com': 1,
    'adadmin.house365.com': 1,
    'adm.86wan.com': 1,
    'adm.jjj8.cn': 1,
    'adm.qzbbs.com': 1,
    'adm.zbinfo.net': 1,
    'adm.zzfish.cn': 1,
    'adp.cnool.net': 1,
    'adsclick.yx.js.cn': 1,
    'aid.chinayk.com': 1,
    'am.szhome.com': 1,
    'biz.gexing.com': 1,
    'btn.onlylady.com': 1,
    'cachead.com': 1,
    'dd.xdnice.com': 1,
    'dfad.dfdaily.com': 1,
    'dg.073img.com': 1,
    'ebpx.renren.com': 1,
    'ecma.bdimg.com': 1,
    'g1.sdo.com': 1,
    'ggg.zj.com': 1,
    'ggw.gusuwang.com': 1,
    'ggw.watertu.com': 1,
    'ifx.aifang.com': 1,
    'img.adsame.liba.com': 1,
    'jmsyzj.com': 1,
    'js.youxi369.com': 1,
    'knnwdyou.com': 1,
    'lxting.com': 1,
    'manads.static.olcdn.com': 1,
    'manage.wdfans.cn': 1,
    'media.cheshi-img.com': 1,
    'money.qz828.com': 1,
    'myad.toocle.com': 1,
    'okm918.com': 1,
    'p.szonline.net': 1,
    'phpad.cqnews.net': 1,
    'pic.0597kk.com': 1,
    'pic.ea3w.com': 1,
    'pic.taian.com': 1,
    'pro.iweihai.cn': 1,
    'pub.funshion.com': 1,
    'publicize.liao1.com': 1,
    'rh.qq.com': 1,
    'same.chinadaily.com.cn': 1,
    'same.stockstar.com': 1,
    'share.gzdsw.com': 1,
    'unionjs.dianxin.com': 1,
    'vupload.duowan.com': 1,
    'wp.ylaop.com': 1,
    'zt2088.com': 1,
    'img.163vv.com': 1,
    'js.duotegame.com': 1,
    'hiad.vmall.com': 1,
    'app.acm.dzwww.com': 1,
    'log.vdisk.cn': 1,
    'analytics-union.xunlei.com': 1
};
function FindProxyForURLByAdblock(url, host) {
    // untrusted ablock plus list, disable whitelist until chinalist come back.
    if (blackhole_host.hasOwnProperty(host)) {
        return 'PROXY 127.0.0.1:8086';
    }
    return 'DIRECT';
}

function FindProxyForURLByAutoProxy(url, host) {
    if (dnsDomainIs(host, ".zx915.com") || host == "zx915.com") return "DIRECT";
    if (dnsDomainIs(host, ".ztgame.com") || host == "ztgame.com") return "DIRECT";
    if (dnsDomainIs(host, ".zqgame.com") || host == "zqgame.com") return "DIRECT";
    if (dnsDomainIs(host, ".zoosnet.net") || host == "zoosnet.net") return "DIRECT";
    if (dnsDomainIs(host, ".zoopda.com") || host == "zoopda.com") return "DIRECT";
    if (dnsDomainIs(host, ".zongheng.com") || host == "zongheng.com") return "DIRECT";
    if (dnsDomainIs(host, ".zhubajie.com") || host == "zhubajie.com") return "DIRECT";
    if (dnsDomainIs(host, ".zhongxingfans.com") || host == "zhongxingfans.com") return "DIRECT";
    if (dnsDomainIs(host, ".zhongsou.net") || host == "zhongsou.net") return "DIRECT";
    if (dnsDomainIs(host, ".zhimg.com") || host == "zhimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".zhihu.com") || host == "zhihu.com") return "DIRECT";
    if (dnsDomainIs(host, ".zhibo8.com") || host == "zhibo8.com") return "DIRECT";
    if (dnsDomainIs(host, ".zhibo8.cc") || host == "zhibo8.cc") return "DIRECT";
    if (dnsDomainIs(host, ".zhi.hu") || host == "zhi.hu") return "DIRECT";
    if (dnsDomainIs(host, ".zhenai.com") || host == "zhenai.com") return "DIRECT";
    if (dnsDomainIs(host, ".zhaopin.com") || host == "zhaopin.com") return "DIRECT";
    if (dnsDomainIs(host, ".zhaodao123.com") || host == "zhaodao123.com") return "DIRECT";
    if (dnsDomainIs(host, ".zdmimg.com") || host == "zdmimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".zdface.com") || host == "zdface.com") return "DIRECT";
    if (dnsDomainIs(host, ".zbjimg.com") || host == "zbjimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".zaojiao.com") || host == "zaojiao.com") return "DIRECT";
    if (dnsDomainIs(host, ".zaobao.com") || host == "zaobao.com") return "DIRECT";
    if (dnsDomainIs(host, ".yyets.com") || host == "yyets.com") return "DIRECT";
    if (dnsDomainIs(host, ".yxlady.com") || host == "yxlady.com") return "DIRECT";
    if (dnsDomainIs(host, ".yupoo.com") || host == "yupoo.com") return "DIRECT";
    if (dnsDomainIs(host, ".youwo123.com") || host == "youwo123.com") return "DIRECT";
    if (dnsDomainIs(host, ".youshang.com") || host == "youshang.com") return "DIRECT";
    if (dnsDomainIs(host, ".youku.com") || host == "youku.com") return "DIRECT";
    if (dnsDomainIs(host, ".yougou.com") || host == "yougou.com") return "DIRECT";
    if (dnsDomainIs(host, ".youdao.com") || host == "youdao.com") return "DIRECT";
    if (dnsDomainIs(host, ".youboy.com") || host == "youboy.com") return "DIRECT";
    if (dnsDomainIs(host, ".yolk7.com") || host == "yolk7.com") return "DIRECT";
    if (dnsDomainIs(host, ".yoka.com") || host == "yoka.com") return "DIRECT";
    if (dnsDomainIs(host, ".yocc.net") || host == "yocc.net") return "DIRECT";
    if (dnsDomainIs(host, ".ynet.com") || host == "ynet.com") return "DIRECT";
    if (dnsDomainIs(host, ".ykimg.com") || host == "ykimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".yiyi.cc") || host == "yiyi.cc") return "DIRECT";
    if (dnsDomainIs(host, ".yixun.com") || host == "yixun.com") return "DIRECT";
    if (dnsDomainIs(host, ".yiqifa.com") || host == "yiqifa.com") return "DIRECT";
    if (dnsDomainIs(host, ".yinyuetai.com") || host == "yinyuetai.com") return "DIRECT";
    if (dnsDomainIs(host, ".yintai.com") || host == "yintai.com") return "DIRECT";
    if (dnsDomainIs(host, ".yingjiesheng.com") || host == "yingjiesheng.com") return "DIRECT";
    if (dnsDomainIs(host, ".yihaodianimg.com") || host == "yihaodianimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".yihaodian.com") || host == "yihaodian.com") return "DIRECT";
    if (dnsDomainIs(host, ".yieldmanager.com") || host == "yieldmanager.com") return "DIRECT";
    if (dnsDomainIs(host, ".yicai.com") || host == "yicai.com") return "DIRECT";
    if (dnsDomainIs(host, ".yhd.com") || host == "yhd.com") return "DIRECT";
    if (dnsDomainIs(host, ".yesky.com") || host == "yesky.com") return "DIRECT";
    if (dnsDomainIs(host, ".ydstatic.com") || host == "ydstatic.com") return "DIRECT";
    if (dnsDomainIs(host, ".yaolan.com") || host == "yaolan.com") return "DIRECT";
    if (dnsDomainIs(host, ".xyxy.net") || host == "xyxy.net") return "DIRECT";
    if (dnsDomainIs(host, ".xunlei.com") || host == "xunlei.com") return "DIRECT";
    if (dnsDomainIs(host, ".xungou.com") || host == "xungou.com") return "DIRECT";
    if (dnsDomainIs(host, ".xtltt.com") || host == "xtltt.com") return "DIRECT";
    if (dnsDomainIs(host, ".xp9365.com") || host == "xp9365.com") return "DIRECT";
    if (dnsDomainIs(host, ".xn--fiqs8s") || host == "xn--fiqs8s") return "DIRECT";
    if (dnsDomainIs(host, ".xmfish.com") || host == "xmfish.com") return "DIRECT";
    if (dnsDomainIs(host, ".xlpan.com") || host == "xlpan.com") return "DIRECT";
    if (dnsDomainIs(host, ".xiyou54.com") || host == "xiyou54.com") return "DIRECT";
    if (dnsDomainIs(host, ".xiyou53.com") || host == "xiyou53.com") return "DIRECT";
    if (dnsDomainIs(host, ".xiu.com") || host == "xiu.com") return "DIRECT";
    if (dnsDomainIs(host, ".xitek.com") || host == "xitek.com") return "DIRECT";
    if (dnsDomainIs(host, ".xinnet.com") || host == "xinnet.com") return "DIRECT";
    if (dnsDomainIs(host, ".xinhuanet.com") || host == "xinhuanet.com") return "DIRECT";
    if (dnsDomainIs(host, ".xilu.com") || host == "xilu.com") return "DIRECT";
    if (dnsDomainIs(host, ".xici.net") || host == "xici.net") return "DIRECT";
    if (dnsDomainIs(host, ".xiazaiba.com") || host == "xiazaiba.com") return "DIRECT";
    if (dnsDomainIs(host, ".xiaonei.com") || host == "xiaonei.com") return "DIRECT";
    if (dnsDomainIs(host, ".xiaomi.com") || host == "xiaomi.com") return "DIRECT";
    if (dnsDomainIs(host, ".xiami.net") || host == "xiami.net") return "DIRECT";
    if (dnsDomainIs(host, ".xiami.com") || host == "xiami.com") return "DIRECT";
    if (dnsDomainIs(host, ".xiachufang.com") || host == "xiachufang.com") return "DIRECT";
    if (dnsDomainIs(host, ".xi666.com") || host == "xi666.com") return "DIRECT";
    if (dnsDomainIs(host, ".xda-china.com") || host == "xda-china.com") return "DIRECT";
    if (dnsDomainIs(host, ".www.renren.com") || host == "www.renren.com") return "DIRECT";
    if (dnsDomainIs(host, ".wumii.com") || host == "wumii.com") return "DIRECT";
    if (dnsDomainIs(host, ".wsj.com") || host == "wsj.com") return "DIRECT";
    if (dnsDomainIs(host, ".wrating.com") || host == "wrating.com") return "DIRECT";
    if (dnsDomainIs(host, ".wordpress.org") || host == "wordpress.org") return "DIRECT";
    if (dnsDomainIs(host, ".woniu.com") || host == "woniu.com") return "DIRECT";
    if (dnsDomainIs(host, ".williamlong.info") || host == "williamlong.info") return "DIRECT";
    if (dnsDomainIs(host, ".whlongda.com") || host == "whlongda.com") return "DIRECT";
    if (dnsDomainIs(host, ".west263.com") || host == "west263.com") return "DIRECT";
    if (dnsDomainIs(host, ".weiphone.com") || host == "weiphone.com") return "DIRECT";
    if (dnsDomainIs(host, ".weibo.com") || host == "weibo.com") return "DIRECT";
    if (dnsDomainIs(host, ".web887.com") || host == "web887.com") return "DIRECT";
    if (dnsDomainIs(host, ".wdjimg.com") || host == "wdjimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".wandoujia.com") || host == "wandoujia.com") return "DIRECT";
    if (dnsDomainIs(host, ".vjia.com") || host == "vjia.com") return "DIRECT";
    if (dnsDomainIs(host, ".vizu.com") || host == "vizu.com") return "DIRECT";
    if (dnsDomainIs(host, ".vipshop.com") || host == "vipshop.com") return "DIRECT";
    if (dnsDomainIs(host, ".verycd.com") || host == "verycd.com") return "DIRECT";
    if (dnsDomainIs(host, ".vcimg.com") || host == "vcimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".vancl.com") || host == "vancl.com") return "DIRECT";
    if (dnsDomainIs(host, ".v2ex.com") || host == "v2ex.com") return "DIRECT";
    if (dnsDomainIs(host, ".v.iask.com") || host == "v.iask.com") return "DIRECT";
    if (dnsDomainIs(host, ".uuzu.com") || host == "uuzu.com") return "DIRECT";
    if (dnsDomainIs(host, ".uuu9.com") || host == "uuu9.com") return "DIRECT";
    if (dnsDomainIs(host, ".uusee.com") || host == "uusee.com") return "DIRECT";
    if (dnsDomainIs(host, ".up2c.com") || host == "up2c.com") return "DIRECT";
    if (dnsDomainIs(host, ".uniontoufang.com") || host == "uniontoufang.com") return "DIRECT";
    if (dnsDomainIs(host, ".umiwi.com") || host == "umiwi.com") return "DIRECT";
    if (dnsDomainIs(host, ".ulink.cc") || host == "ulink.cc") return "DIRECT";
    if (dnsDomainIs(host, ".ucjoy.com") || host == "ucjoy.com") return "DIRECT";
    if (dnsDomainIs(host, ".u17.com") || host == "u17.com") return "DIRECT";
    if (dnsDomainIs(host, ".twcczhu.com") || host == "twcczhu.com") return "DIRECT";
    if (dnsDomainIs(host, ".tvmao.com") || host == "tvmao.com") return "DIRECT";
    if (dnsDomainIs(host, ".tuniu.com") || host == "tuniu.com") return "DIRECT";
    if (dnsDomainIs(host, ".tui18.com") || host == "tui18.com") return "DIRECT";
    if (dnsDomainIs(host, ".tudouui.com") || host == "tudouui.com") return "DIRECT";
    if (dnsDomainIs(host, ".tudou.com") || host == "tudou.com") return "DIRECT";
    if (dnsDomainIs(host, ".tuan800.com") || host == "tuan800.com") return "DIRECT";
    if (dnsDomainIs(host, ".tremormedia.com") || host == "tremormedia.com") return "DIRECT";
    if (dnsDomainIs(host, ".toocle.com") || host == "toocle.com") return "DIRECT";
    if (dnsDomainIs(host, ".tom.com") || host == "tom.com") return "DIRECT";
    if (dnsDomainIs(host, ".tmall.com") || host == "tmall.com") return "DIRECT";
    if (dnsDomainIs(host, ".tlbbsifu.com") || host == "tlbbsifu.com") return "DIRECT";
    if (dnsDomainIs(host, ".tlbb8.com") || host == "tlbb8.com") return "DIRECT";
    if (dnsDomainIs(host, ".tlbb2.com") || host == "tlbb2.com") return "DIRECT";
    if (dnsDomainIs(host, ".titan24.com") || host == "titan24.com") return "DIRECT";
    if (dnsDomainIs(host, ".tiexue.net") || host == "tiexue.net") return "DIRECT";
    if (dnsDomainIs(host, ".tiebaimg.com") || host == "tiebaimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".tiao8.info") || host == "tiao8.info") return "DIRECT";
    if (dnsDomainIs(host, ".tianyaui.com") || host == "tianyaui.com") return "DIRECT";
    if (dnsDomainIs(host, ".tianji.com") || host == "tianji.com") return "DIRECT";
    if (dnsDomainIs(host, ".tiancity.com") || host == "tiancity.com") return "DIRECT";
    if (dnsDomainIs(host, ".thethirdmedia.com") || host == "thethirdmedia.com") return "DIRECT";
    if (dnsDomainIs(host, ".theplanet.com") || host == "theplanet.com") return "DIRECT";
    if (dnsDomainIs(host, ".thawte.com") || host == "thawte.com") return "DIRECT";
    if (dnsDomainIs(host, ".tgbus.com") || host == "tgbus.com") return "DIRECT";
    if (dnsDomainIs(host, ".tenpay.com") || host == "tenpay.com") return "DIRECT";
    if (dnsDomainIs(host, ".tencent.com") || host == "tencent.com") return "DIRECT";
    if (dnsDomainIs(host, ".tdimg.com") || host == "tdimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".tbcache.com") || host == "tbcache.com") return "DIRECT";
    if (dnsDomainIs(host, ".taobaocdn.com") || host == "taobaocdn.com") return "DIRECT";
    if (dnsDomainIs(host, ".taobao.com") || host == "taobao.com") return "DIRECT";
    if (dnsDomainIs(host, ".tao123.com") || host == "tao123.com") return "DIRECT";
    if (dnsDomainIs(host, ".tanx.com") || host == "tanx.com") return "DIRECT";
    if (dnsDomainIs(host, ".tangdou.com") || host == "tangdou.com") return "DIRECT";
    if (dnsDomainIs(host, ".sznews.com") || host == "sznews.com") return "DIRECT";
    if (dnsDomainIs(host, ".szhome.com") || host == "szhome.com") return "DIRECT";
    if (dnsDomainIs(host, ".synacast.com") || host == "synacast.com") return "DIRECT";
    if (dnsDomainIs(host, ".suning.com") || host == "suning.com") return "DIRECT";
    if (dnsDomainIs(host, ".sttlbb.com") || host == "sttlbb.com") return "DIRECT";
    if (dnsDomainIs(host, ".stockstar.com") || host == "stockstar.com") return "DIRECT";
    if (dnsDomainIs(host, ".staticsdo.com") || host == "staticsdo.com") return "DIRECT";
    if (dnsDomainIs(host, ".stackoverflow.com") || host == "stackoverflow.com") return "DIRECT";
    if (dnsDomainIs(host, ".soufunimg.com") || host == "soufunimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".soufun.com") || host == "soufun.com") return "DIRECT";
    if (dnsDomainIs(host, ".soso.com") || host == "soso.com") return "DIRECT";
    if (dnsDomainIs(host, ".sootoo.com") || host == "sootoo.com") return "DIRECT";
    if (dnsDomainIs(host, ".soku.com") || host == "soku.com") return "DIRECT";
    if (dnsDomainIs(host, ".sohu.com") || host == "sohu.com") return "DIRECT";
    if (dnsDomainIs(host, ".sogou.com") || host == "sogou.com") return "DIRECT";
    if (dnsDomainIs(host, ".sodu.org") || host == "sodu.org") return "DIRECT";
    if (dnsDomainIs(host, ".snyu.com") || host == "snyu.com") return "DIRECT";
    if (dnsDomainIs(host, ".snsfun.cc") || host == "snsfun.cc") return "DIRECT";
    if (dnsDomainIs(host, ".smzdm.com") || host == "smzdm.com") return "DIRECT";
    if (dnsDomainIs(host, ".skycn.com") || host == "skycn.com") return "DIRECT";
    if (dnsDomainIs(host, ".sj-tl.com") || host == "sj-tl.com") return "DIRECT";
    if (dnsDomainIs(host, ".sinajs.com") || host == "sinajs.com") return "DIRECT";
    if (dnsDomainIs(host, ".sinaimg.com") || host == "sinaimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".sinahk.net") || host == "sinahk.net") return "DIRECT";
    if (dnsDomainIs(host, ".sinaedge.com") || host == "sinaedge.com") return "DIRECT";
    if (dnsDomainIs(host, ".sinaapp.com") || host == "sinaapp.com") return "DIRECT";
    if (dnsDomainIs(host, ".sina.com") || host == "sina.com") return "DIRECT";
    if (dnsDomainIs(host, ".si.kz") || host == "si.kz") return "DIRECT";
    if (dnsDomainIs(host, ".shuangtv.net") || host == "shuangtv.net") return "DIRECT";
    if (dnsDomainIs(host, ".shangdu.com") || host == "shangdu.com") return "DIRECT";
    if (dnsDomainIs(host, ".sg560.com") || host == "sg560.com") return "DIRECT";
    if (dnsDomainIs(host, ".sf-express.com") || host == "sf-express.com") return "DIRECT";
    if (dnsDomainIs(host, ".serving-sys.com") || host == "serving-sys.com") return "DIRECT";
    if (dnsDomainIs(host, ".seowhy.com") || host == "seowhy.com") return "DIRECT";
    if (dnsDomainIs(host, ".sdo.com") || host == "sdo.com") return "DIRECT";
    if (dnsDomainIs(host, ".scorecardresearch.com") || host == "scorecardresearch.com") return "DIRECT";
    if (dnsDomainIs(host, ".scanscout.com") || host == "scanscout.com") return "DIRECT";
    if (dnsDomainIs(host, ".sanguosha.com") || host == "sanguosha.com") return "DIRECT";
    if (dnsDomainIs(host, ".rtbidder.net") || host == "rtbidder.net") return "DIRECT";
    if (dnsDomainIs(host, ".rrimg.com") || host == "rrimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".renren.com") || host == "renren.com") return "DIRECT";
    if (dnsDomainIs(host, ".readnovel.com") || host == "readnovel.com") return "DIRECT";
    if (dnsDomainIs(host, ".ranwen.com") || host == "ranwen.com") return "DIRECT";
    if (dnsDomainIs(host, ".rakuten.co.jp") || host == "rakuten.co.jp") return "DIRECT";
    if (dnsDomainIs(host, ".qvbuy.com") || host == "qvbuy.com") return "DIRECT";
    if (dnsDomainIs(host, ".qunar.com") || host == "qunar.com") return "DIRECT";
    if (dnsDomainIs(host, ".quantserve.com") || host == "quantserve.com") return "DIRECT";
    if (dnsDomainIs(host, ".qstatic.com") || host == "qstatic.com") return "DIRECT";
    if (dnsDomainIs(host, ".qqmail.com") || host == "qqmail.com") return "DIRECT";
    if (dnsDomainIs(host, ".qq937.com") || host == "qq937.com") return "DIRECT";
    if (dnsDomainIs(host, ".qq.com") || host == "qq.com") return "DIRECT";
    if (dnsDomainIs(host, ".qjy168.com") || host == "qjy168.com") return "DIRECT";
    if (dnsDomainIs(host, ".qiyou.com") || host == "qiyou.com") return "DIRECT";
    if (dnsDomainIs(host, ".qiyipic.com") || host == "qiyipic.com") return "DIRECT";
    if (dnsDomainIs(host, ".qiyi.com") || host == "qiyi.com") return "DIRECT";
    if (dnsDomainIs(host, ".qiushibaike.com") || host == "qiushibaike.com") return "DIRECT";
    if (dnsDomainIs(host, ".qire123.com") || host == "qire123.com") return "DIRECT";
    if (dnsDomainIs(host, ".qiniucdn.com") || host == "qiniucdn.com") return "DIRECT";
    if (dnsDomainIs(host, ".qingdaonews.com") || host == "qingdaonews.com") return "DIRECT";
    if (dnsDomainIs(host, ".qidian.com") || host == "qidian.com") return "DIRECT";
    if (dnsDomainIs(host, ".qianlong.com") || host == "qianlong.com") return "DIRECT";
    if (dnsDomainIs(host, ".q150.com") || host == "q150.com") return "DIRECT";
    if (dnsDomainIs(host, ".pubmatic.com") || host == "pubmatic.com") return "DIRECT";
    if (dnsDomainIs(host, ".ptlogin2.qq.com") || host == "ptlogin2.qq.com") return "DIRECT";
    if (dnsDomainIs(host, ".pr56789.com") || host == "pr56789.com") return "DIRECT";
    if (dnsDomainIs(host, ".pptv.com") || host == "pptv.com") return "DIRECT";
    if (dnsDomainIs(host, ".ppstream.com") || host == "ppstream.com") return "DIRECT";
    if (dnsDomainIs(host, ".pplive.com") || host == "pplive.com") return "DIRECT";
    if (dnsDomainIs(host, ".pp.cc") || host == "pp.cc") return "DIRECT";
    if (dnsDomainIs(host, ".popgo.org") || host == "popgo.org") return "DIRECT";
    if (dnsDomainIs(host, ".pixlr.com") || host == "pixlr.com") return "DIRECT";
    if (dnsDomainIs(host, ".pingan.com") || host == "pingan.com") return "DIRECT";
    if (dnsDomainIs(host, ".phpwind.net") || host == "phpwind.net") return "DIRECT";
    if (dnsDomainIs(host, ".php100.com") || host == "php100.com") return "DIRECT";
    if (dnsDomainIs(host, ".pengyou.com") || host == "pengyou.com") return "DIRECT";
    if (dnsDomainIs(host, ".pcpop.com") || host == "pcpop.com") return "DIRECT";
    if (dnsDomainIs(host, ".pchome.net") || host == "pchome.net") return "DIRECT";
    if (dnsDomainIs(host, ".pcbeta.com") || host == "pcbeta.com") return "DIRECT";
    if (dnsDomainIs(host, ".paypal.com") || host == "paypal.com") return "DIRECT";
    if (dnsDomainIs(host, ".paipai.com") || host == "paipai.com") return "DIRECT";
    if (dnsDomainIs(host, ".p5w.net") || host == "p5w.net") return "DIRECT";
    if (dnsDomainIs(host, ".otwan.com") || host == "otwan.com") return "DIRECT";
    if (dnsDomainIs(host, ".oschina.net") || host == "oschina.net") return "DIRECT";
    if (dnsDomainIs(host, ".optaim.com") || host == "optaim.com") return "DIRECT";
    if (dnsDomainIs(host, ".onlylady.com") || host == "onlylady.com") return "DIRECT";
    if (dnsDomainIs(host, ".onlinedown.net") || host == "onlinedown.net") return "DIRECT";
    if (dnsDomainIs(host, ".onetad.com") || host == "onetad.com") return "DIRECT";
    if (dnsDomainIs(host, ".okooo.com") || host == "okooo.com") return "DIRECT";
    if (dnsDomainIs(host, ".okhqb.com") || host == "okhqb.com") return "DIRECT";
    if (dnsDomainIs(host, ".okbuy.com") || host == "okbuy.com") return "DIRECT";
    if (dnsDomainIs(host, ".oeeee.com") || host == "oeeee.com") return "DIRECT";
    if (dnsDomainIs(host, ".oadz.com") || host == "oadz.com") return "DIRECT";
    if (dnsDomainIs(host, ".nuomi.com") || host == "nuomi.com") return "DIRECT";
    if (dnsDomainIs(host, ".nowec.com") || host == "nowec.com") return "DIRECT";
    if (dnsDomainIs(host, ".njobt.com") || host == "njobt.com") return "DIRECT";
    if (dnsDomainIs(host, ".nipic.com") || host == "nipic.com") return "DIRECT";
    if (dnsDomainIs(host, ".ngacn.cc") || host == "ngacn.cc") return "DIRECT";
    if (dnsDomainIs(host, ".newsmth.net") || host == "newsmth.net") return "DIRECT";
    if (dnsDomainIs(host, ".netease.com") || host == "netease.com") return "DIRECT";
    if (dnsDomainIs(host, ".net114.com") || host == "net114.com") return "DIRECT";
    if (dnsDomainIs(host, ".nbweekly.com") || host == "nbweekly.com") return "DIRECT";
    if (dnsDomainIs(host, ".mydrivers.com") || host == "mydrivers.com") return "DIRECT";
    if (dnsDomainIs(host, ".my.cl.ly") || host == "my.cl.ly") return "DIRECT";
    if (dnsDomainIs(host, ".mumayi.com") || host == "mumayi.com") return "DIRECT";
    if (dnsDomainIs(host, ".mtime.com") || host == "mtime.com") return "DIRECT";
    if (dnsDomainIs(host, ".msn.com") || host == "msn.com") return "DIRECT";
    if (dnsDomainIs(host, ".mplife.com") || host == "mplife.com") return "DIRECT";
    if (dnsDomainIs(host, ".mozilla.org") || host == "mozilla.org") return "DIRECT";
    if (dnsDomainIs(host, ".mosso.com") || host == "mosso.com") return "DIRECT";
    if (dnsDomainIs(host, ".mop.com") || host == "mop.com") return "DIRECT";
    if (dnsDomainIs(host, ".moonbasa.com") || host == "moonbasa.com") return "DIRECT";
    if (dnsDomainIs(host, ".mookie1.com") || host == "mookie1.com") return "DIRECT";
    if (dnsDomainIs(host, ".mogujie.com") || host == "mogujie.com") return "DIRECT";
    if (dnsDomainIs(host, ".mnwan.com") || host == "mnwan.com") return "DIRECT";
    if (dnsDomainIs(host, ".mmstat.com") || host == "mmstat.com") return "DIRECT";
    if (dnsDomainIs(host, ".mlt01.com") || host == "mlt01.com") return "DIRECT";
    if (dnsDomainIs(host, ".miercn.com") || host == "miercn.com") return "DIRECT";
    if (dnsDomainIs(host, ".microsoft.com") || host == "microsoft.com") return "DIRECT";
    if (dnsDomainIs(host, ".miaozhen.com") || host == "miaozhen.com") return "DIRECT";
    if (dnsDomainIs(host, ".meizu.com") || host == "meizu.com") return "DIRECT";
    if (dnsDomainIs(host, ".meituan.com") || host == "meituan.com") return "DIRECT";
    if (dnsDomainIs(host, ".meishichina.com") || host == "meishichina.com") return "DIRECT";
    if (dnsDomainIs(host, ".meilishuo.com") || host == "meilishuo.com") return "DIRECT";
    if (dnsDomainIs(host, ".meilele.com") || host == "meilele.com") return "DIRECT";
    if (dnsDomainIs(host, ".mediav.com") || host == "mediav.com") return "DIRECT";
    if (dnsDomainIs(host, ".mediaplex.com") || host == "mediaplex.com") return "DIRECT";
    if (dnsDomainIs(host, ".mathtag.com") || host == "mathtag.com") return "DIRECT";
    if (dnsDomainIs(host, ".mapbar.com") || host == "mapbar.com") return "DIRECT";
    if (dnsDomainIs(host, ".mapabc.com") || host == "mapabc.com") return "DIRECT";
    if (dnsDomainIs(host, ".manzuo.com") || host == "manzuo.com") return "DIRECT";
    if (dnsDomainIs(host, ".mangocity.com") || host == "mangocity.com") return "DIRECT";
    if (dnsDomainIs(host, ".makepolo.com") || host == "makepolo.com") return "DIRECT";
    if (dnsDomainIs(host, ".made-in-china.com") || host == "made-in-china.com") return "DIRECT";
    if (dnsDomainIs(host, ".m1905.com") || host == "m1905.com") return "DIRECT";
    if (dnsDomainIs(host, ".m18.com") || host == "m18.com") return "DIRECT";
    if (dnsDomainIs(host, ".lygo.com") || host == "lygo.com") return "DIRECT";
    if (dnsDomainIs(host, ".lycos.com") || host == "lycos.com") return "DIRECT";
    if (dnsDomainIs(host, ".lxdns.com") || host == "lxdns.com") return "DIRECT";
    if (dnsDomainIs(host, ".lvping.com") || host == "lvping.com") return "DIRECT";
    if (dnsDomainIs(host, ".lusongsong.com") || host == "lusongsong.com") return "DIRECT";
    if (dnsDomainIs(host, ".love21cn.com") || host == "love21cn.com") return "DIRECT";
    if (dnsDomainIs(host, ".longhoo.net") || host == "longhoo.net") return "DIRECT";
    if (dnsDomainIs(host, ".loli.vg") || host == "loli.vg") return "DIRECT";
    if (dnsDomainIs(host, ".loli.mg") || host == "loli.mg") return "DIRECT";
    if (dnsDomainIs(host, ".lohas.ly") || host == "lohas.ly") return "DIRECT";
    if (dnsDomainIs(host, ".logmein.com") || host == "logmein.com") return "DIRECT";
    if (dnsDomainIs(host, ".localhost") || host == "localhost") return "DIRECT";
    if (dnsDomainIs(host, ".local") || host == "local") return "DIRECT";
    if (dnsDomainIs(host, ".live.com") || host == "live.com") return "DIRECT";
    if (dnsDomainIs(host, ".linkedin.com") || host == "linkedin.com") return "DIRECT";
    if (dnsDomainIs(host, ".linezing.com") || host == "linezing.com") return "DIRECT";
    if (dnsDomainIs(host, ".lietou.com") || host == "lietou.com") return "DIRECT";
    if (dnsDomainIs(host, ".liebiao.com") || host == "liebiao.com") return "DIRECT";
    if (dnsDomainIs(host, ".lewatek.com") || host == "lewatek.com") return "DIRECT";
    if (dnsDomainIs(host, ".lewaos.com") || host == "lewaos.com") return "DIRECT";
    if (dnsDomainIs(host, ".letv.com") || host == "letv.com") return "DIRECT";
    if (dnsDomainIs(host, ".letao.com") || host == "letao.com") return "DIRECT";
    if (dnsDomainIs(host, ".leho.com") || host == "leho.com") return "DIRECT";
    if (dnsDomainIs(host, ".lehecai.com") || host == "lehecai.com") return "DIRECT";
    if (dnsDomainIs(host, ".legolas-media.com") || host == "legolas-media.com") return "DIRECT";
    if (dnsDomainIs(host, ".lashouimg.com") || host == "lashouimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".lashou.com") || host == "lashou.com") return "DIRECT";
    if (dnsDomainIs(host, ".lampdrive.com") || host == "lampdrive.com") return "DIRECT";
    if (dnsDomainIs(host, ".lafaso.com") || host == "lafaso.com") return "DIRECT";
    if (dnsDomainIs(host, ".lady8844.com") || host == "lady8844.com") return "DIRECT";
    if (dnsDomainIs(host, ".l99.com") || host == "l99.com") return "DIRECT";
    if (dnsDomainIs(host, ".kugou.com") || host == "kugou.com") return "DIRECT";
    if (dnsDomainIs(host, ".kuaiwan.com") || host == "kuaiwan.com") return "DIRECT";
    if (dnsDomainIs(host, ".kuaidi100.com") || host == "kuaidi100.com") return "DIRECT";
    if (dnsDomainIs(host, ".ku6img.com") || host == "ku6img.com") return "DIRECT";
    if (dnsDomainIs(host, ".ku6cdn.com") || host == "ku6cdn.com") return "DIRECT";
    if (dnsDomainIs(host, ".ku6.com") || host == "ku6.com") return "DIRECT";
    if (dnsDomainIs(host, ".koudai8.com") || host == "koudai8.com") return "DIRECT";
    if (dnsDomainIs(host, ".kimiss.com") || host == "kimiss.com") return "DIRECT";
    if (dnsDomainIs(host, ".keyunzhan.com") || host == "keyunzhan.com") return "DIRECT";
    if (dnsDomainIs(host, ".kdnet.net") || host == "kdnet.net") return "DIRECT";
    if (dnsDomainIs(host, ".kankan.com") || host == "kankan.com") return "DIRECT";
    if (dnsDomainIs(host, ".kanimg.com") || host == "kanimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".kandian.net") || host == "kandian.net") return "DIRECT";
    if (dnsDomainIs(host, ".kandian.com") || host == "kandian.com") return "DIRECT";
    if (dnsDomainIs(host, ".kaixin001.com") || host == "kaixin001.com") return "DIRECT";
    if (dnsDomainIs(host, ".jysq.net") || host == "jysq.net") return "DIRECT";
    if (dnsDomainIs(host, ".jxedt.com") || host == "jxedt.com") return "DIRECT";
    if (dnsDomainIs(host, ".junshijia.com") || host == "junshijia.com") return "DIRECT";
    if (dnsDomainIs(host, ".jumei.com") || host == "jumei.com") return "DIRECT";
    if (dnsDomainIs(host, ".jstv.com") || host == "jstv.com") return "DIRECT";
    if (dnsDomainIs(host, ".jqw.com") || host == "jqw.com") return "DIRECT";
    if (dnsDomainIs(host, ".joqoo.com") || host == "joqoo.com") return "DIRECT";
    if (dnsDomainIs(host, ".jjwxc.net") || host == "jjwxc.net") return "DIRECT";
    if (dnsDomainIs(host, ".jiuyaoyouxi.com") || host == "jiuyaoyouxi.com") return "DIRECT";
    if (dnsDomainIs(host, ".jinti.com") || host == "jinti.com") return "DIRECT";
    if (dnsDomainIs(host, ".jing.fm") || host == "jing.fm") return "DIRECT";
    if (dnsDomainIs(host, ".jiepang.com") || host == "jiepang.com") return "DIRECT";
    if (dnsDomainIs(host, ".jiayuan.com") || host == "jiayuan.com") return "DIRECT";
    if (dnsDomainIs(host, ".jiatx.com") || host == "jiatx.com") return "DIRECT";
    if (dnsDomainIs(host, ".jiathis.com") || host == "jiathis.com") return "DIRECT";
    if (dnsDomainIs(host, ".jd.com") || host == "jd.com") return "DIRECT";
    if (dnsDomainIs(host, ".jb51.net") || host == "jb51.net") return "DIRECT";
    if (dnsDomainIs(host, ".jandan.net") || host == "jandan.net") return "DIRECT";
    if (dnsDomainIs(host, ".james520.com") || host == "james520.com") return "DIRECT";
    if (dnsDomainIs(host, ".iyaya.com") || host == "iyaya.com") return "DIRECT";
    if (dnsDomainIs(host, ".iweek.ly") || host == "iweek.ly") return "DIRECT";
    if (dnsDomainIs(host, ".iteye.com") || host == "iteye.com") return "DIRECT";
    if (dnsDomainIs(host, ".it168.com") || host == "it168.com") return "DIRECT";
    if (dnsDomainIs(host, ".is686.com") || host == "is686.com") return "DIRECT";
    if (dnsDomainIs(host, ".irs01.net") || host == "irs01.net") return "DIRECT";
    if (dnsDomainIs(host, ".irs01.com") || host == "irs01.com") return "DIRECT";
    if (dnsDomainIs(host, ".iqiyi.com") || host == "iqiyi.com") return "DIRECT";
    if (dnsDomainIs(host, ".iqilu.com") || host == "iqilu.com") return "DIRECT";
    if (dnsDomainIs(host, ".ipinyou.com") || host == "ipinyou.com") return "DIRECT";
    if (dnsDomainIs(host, ".ip138.com") || host == "ip138.com") return "DIRECT";
    if (dnsDomainIs(host, ".invitemedia.com") || host == "invitemedia.com") return "DIRECT";
    if (dnsDomainIs(host, ".infzm.com") || host == "infzm.com") return "DIRECT";
    if (dnsDomainIs(host, ".inc.gs") || host == "inc.gs") return "DIRECT";
    if (dnsDomainIs(host, ".imrworldwide.com") || host == "imrworldwide.com") return "DIRECT";
    if (dnsDomainIs(host, ".img.cctvpic.com") || host == "img.cctvpic.com") return "DIRECT";
    if (dnsDomainIs(host, ".img-space.com") || host == "img-space.com") return "DIRECT";
    if (dnsDomainIs(host, ".imanhua.com") || host == "imanhua.com") return "DIRECT";
    if (dnsDomainIs(host, ".images-cn.ssl-images-amazon.com") || host == "images-cn.ssl-images-amazon.com") return "DIRECT";
    if (dnsDomainIs(host, ".images-amazon.com") || host == "images-amazon.com") return "DIRECT";
    if (dnsDomainIs(host, ".im286.com") || host == "im286.com") return "DIRECT";
    if (dnsDomainIs(host, ".iloveyouxi.com") || host == "iloveyouxi.com") return "DIRECT";
    if (dnsDomainIs(host, ".ijinshan.com") || host == "ijinshan.com") return "DIRECT";
    if (dnsDomainIs(host, ".ifensi.com") || host == "ifensi.com") return "DIRECT";
    if (dnsDomainIs(host, ".ifengimg.com") || host == "ifengimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".ifeng.com") || host == "ifeng.com") return "DIRECT";
    if (dnsDomainIs(host, ".idailyapp.com") || host == "idailyapp.com") return "DIRECT";
    if (dnsDomainIs(host, ".icson.com") || host == "icson.com") return "DIRECT";
    if (dnsDomainIs(host, ".iciba.com") || host == "iciba.com") return "DIRECT";
    if (dnsDomainIs(host, ".ibm.com") || host == "ibm.com") return "DIRECT";
    if (dnsDomainIs(host, ".iask.com") || host == "iask.com") return "DIRECT";
    if (dnsDomainIs(host, ".hupu.com") || host == "hupu.com") return "DIRECT";
    if (dnsDomainIs(host, ".huochepiao.com") || host == "huochepiao.com") return "DIRECT";
    if (dnsDomainIs(host, ".hudong.com") || host == "hudong.com") return "DIRECT";
    if (dnsDomainIs(host, ".huanqiu.com") || host == "huanqiu.com") return "DIRECT";
    if (dnsDomainIs(host, ".huaban.com") || host == "huaban.com") return "DIRECT";
    if (dnsDomainIs(host, ".house365.com") || host == "house365.com") return "DIRECT";
    if (dnsDomainIs(host, ".hotsales.net") || host == "hotsales.net") return "DIRECT";
    if (dnsDomainIs(host, ".hoopchina.com") || host == "hoopchina.com") return "DIRECT";
    if (dnsDomainIs(host, ".homeinns.com") || host == "homeinns.com") return "DIRECT";
    if (dnsDomainIs(host, ".hlwan.net") || host == "hlwan.net") return "DIRECT";
    if (dnsDomainIs(host, ".hichina.com") || host == "hichina.com") return "DIRECT";
    if (dnsDomainIs(host, ".hiapk.com") || host == "hiapk.com") return "DIRECT";
    if (dnsDomainIs(host, ".hi-pda.com") || host == "hi-pda.com") return "DIRECT";
    if (dnsDomainIs(host, ".hf365.com") || host == "hf365.com") return "DIRECT";
    if (dnsDomainIs(host, ".help.apple.com") || host == "help.apple.com") return "DIRECT";
    if (dnsDomainIs(host, ".hefei.cc") || host == "hefei.cc") return "DIRECT";
    if (dnsDomainIs(host, ".hdslb.com") || host == "hdslb.com") return "DIRECT";
    if (dnsDomainIs(host, ".hc360.com") || host == "hc360.com") return "DIRECT";
    if (dnsDomainIs(host, ".harrenmedianetwork.com") || host == "harrenmedianetwork.com") return "DIRECT";
    if (dnsDomainIs(host, ".haodf.com") || host == "haodf.com") return "DIRECT";
    if (dnsDomainIs(host, ".hao123.com") || host == "hao123.com") return "DIRECT";
    if (dnsDomainIs(host, ".haliyuya.com") || host == "haliyuya.com") return "DIRECT";
    if (dnsDomainIs(host, ".gzmama.com") || host == "gzmama.com") return "DIRECT";
    if (dnsDomainIs(host, ".gy9y.com") || host == "gy9y.com") return "DIRECT";
    if (dnsDomainIs(host, ".gtimg.com") || host == "gtimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".gougou.com") || host == "gougou.com") return "DIRECT";
    if (dnsDomainIs(host, ".google-analytics.com") || host == "google-analytics.com") return "DIRECT";
    if (dnsDomainIs(host, ".goodbabygroup.com") || host == "goodbabygroup.com") return "DIRECT";
    if (dnsDomainIs(host, ".gongchang.com") || host == "gongchang.com") return "DIRECT";
    if (dnsDomainIs(host, ".go2map.com") || host == "go2map.com") return "DIRECT";
    if (dnsDomainIs(host, ".ggmm777.com") || host == "ggmm777.com") return "DIRECT";
    if (dnsDomainIs(host, ".gfw.io") || host == "gfw.io") return "DIRECT";
    if (dnsDomainIs(host, ".gfan.com") || host == "gfan.com") return "DIRECT";
    if (dnsDomainIs(host, ".getfirebug.com") || host == "getfirebug.com") return "DIRECT";
    if (dnsDomainIs(host, ".gaopeng.com") || host == "gaopeng.com") return "DIRECT";
    if (dnsDomainIs(host, ".ganji.com") || host == "ganji.com") return "DIRECT";
    if (dnsDomainIs(host, ".gamewan.net") || host == "gamewan.net") return "DIRECT";
    if (dnsDomainIs(host, ".gamesville.com") || host == "gamesville.com") return "DIRECT";
    if (dnsDomainIs(host, ".gamestlbb.com") || host == "gamestlbb.com") return "DIRECT";
    if (dnsDomainIs(host, ".gamersky.com") || host == "gamersky.com") return "DIRECT";
    if (dnsDomainIs(host, ".game3896.com") || host == "game3896.com") return "DIRECT";
    if (dnsDomainIs(host, ".game3737.com") || host == "game3737.com") return "DIRECT";
    if (dnsDomainIs(host, ".fx120.net") || host == "fx120.net") return "DIRECT";
    if (dnsDomainIs(host, ".funshion.com") || host == "funshion.com") return "DIRECT";
    if (dnsDomainIs(host, ".ftuan.com") || host == "ftuan.com") return "DIRECT";
    if (dnsDomainIs(host, ".ftchinese.com") || host == "ftchinese.com") return "DIRECT";
    if (dnsDomainIs(host, ".fobshanghai.com") || host == "fobshanghai.com") return "DIRECT";
    if (dnsDomainIs(host, ".flickr.com") || host == "flickr.com") return "DIRECT";
    if (dnsDomainIs(host, ".ffdy.cc") || host == "ffdy.cc") return "DIRECT";
    if (dnsDomainIs(host, ".fenzhi.com") || host == "fenzhi.com") return "DIRECT";
    if (dnsDomainIs(host, ".fengniao.com") || host == "fengniao.com") return "DIRECT";
    if (dnsDomainIs(host, ".fblife.com") || host == "fblife.com") return "DIRECT";
    if (dnsDomainIs(host, ".fat999.com") || host == "fat999.com") return "DIRECT";
    if (dnsDomainIs(host, ".fastif.net") || host == "fastif.net") return "DIRECT";
    if (dnsDomainIs(host, ".fastcdn.com") || host == "fastcdn.com") return "DIRECT";
    if (dnsDomainIs(host, ".fantong.com") || host == "fantong.com") return "DIRECT";
    if (dnsDomainIs(host, ".eyoudi.com") || host == "eyoudi.com") return "DIRECT";
    if (dnsDomainIs(host, ".eye.rs") || host == "eye.rs") return "DIRECT";
    if (dnsDomainIs(host, ".exam8.com") || host == "exam8.com") return "DIRECT";
    if (dnsDomainIs(host, ".etao.com") || host == "etao.com") return "DIRECT";
    if (dnsDomainIs(host, ".et8.org") || host == "et8.org") return "DIRECT";
    if (dnsDomainIs(host, ".ename.net") || host == "ename.net") return "DIRECT";
    if (dnsDomainIs(host, ".elong.com") || host == "elong.com") return "DIRECT";
    if (dnsDomainIs(host, ".ellechina.com") || host == "ellechina.com") return "DIRECT";
    if (dnsDomainIs(host, ".egou.com") || host == "egou.com") return "DIRECT";
    if (dnsDomainIs(host, ".ecitic.com") || host == "ecitic.com") return "DIRECT";
    if (dnsDomainIs(host, ".ebay.com") || host == "ebay.com") return "DIRECT";
    if (dnsDomainIs(host, ".eb80.com") || host == "eb80.com") return "DIRECT";
    if (dnsDomainIs(host, ".eastmoney.com") || host == "eastmoney.com") return "DIRECT";
    if (dnsDomainIs(host, ".eastday.com") || host == "eastday.com") return "DIRECT";
    if (dnsDomainIs(host, ".dzwww.com") || host == "dzwww.com") return "DIRECT";
    if (dnsDomainIs(host, ".dytt8.net") || host == "dytt8.net") return "DIRECT";
    if (dnsDomainIs(host, ".dy2018.com") || host == "dy2018.com") return "DIRECT";
    if (dnsDomainIs(host, ".duowan.com") || host == "duowan.com") return "DIRECT";
    if (dnsDomainIs(host, ".duote.com") || host == "duote.com") return "DIRECT";
    if (dnsDomainIs(host, ".duomi.com") || host == "duomi.com") return "DIRECT";
    if (dnsDomainIs(host, ".duba.net") || host == "duba.net") return "DIRECT";
    if (dnsDomainIs(host, ".duapp.com") || host == "duapp.com") return "DIRECT";
    if (dnsDomainIs(host, ".dream4ever.org") || host == "dream4ever.org") return "DIRECT";
    if (dnsDomainIs(host, ".dpfile.com") || host == "dpfile.com") return "DIRECT";
    if (dnsDomainIs(host, ".doubleclick.net") || host == "doubleclick.net") return "DIRECT";
    if (dnsDomainIs(host, ".doubleclick.com") || host == "doubleclick.com") return "DIRECT";
    if (dnsDomainIs(host, ".douban.fm") || host == "douban.fm") return "DIRECT";
    if (dnsDomainIs(host, ".douban.com") || host == "douban.com") return "DIRECT";
    if (dnsDomainIs(host, ".dospy.com") || host == "dospy.com") return "DIRECT";
    if (dnsDomainIs(host, ".donews.com") || host == "donews.com") return "DIRECT";
    if (dnsDomainIs(host, ".doctorcom.com") || host == "doctorcom.com") return "DIRECT";
    if (dnsDomainIs(host, ".docin.com") || host == "docin.com") return "DIRECT";
    if (dnsDomainIs(host, ".doc88.com") || host == "doc88.com") return "DIRECT";
    if (dnsDomainIs(host, ".dmhy.org") || host == "dmhy.org") return "DIRECT";
    if (dnsDomainIs(host, ".discuz.net") || host == "discuz.net") return "DIRECT";
    if (dnsDomainIs(host, ".dipan.com") || host == "dipan.com") return "DIRECT";
    if (dnsDomainIs(host, ".didatuan.com") || host == "didatuan.com") return "DIRECT";
    if (dnsDomainIs(host, ".dianping.com") || host == "dianping.com") return "DIRECT";
    if (dnsDomainIs(host, ".diandian.com") || host == "diandian.com") return "DIRECT";
    if (dnsDomainIs(host, ".dh818.com") || host == "dh818.com") return "DIRECT";
    if (dnsDomainIs(host, ".dedecms.com") || host == "dedecms.com") return "DIRECT";
    if (dnsDomainIs(host, ".ddmap.com") || host == "ddmap.com") return "DIRECT";
    if (dnsDomainIs(host, ".dbank.com") || host == "dbank.com") return "DIRECT";
    if (dnsDomainIs(host, ".dayoo.com") || host == "dayoo.com") return "DIRECT";
    if (dnsDomainIs(host, ".daqi.com") || host == "daqi.com") return "DIRECT";
    if (dnsDomainIs(host, ".dangdang.com") || host == "dangdang.com") return "DIRECT";
    if (dnsDomainIs(host, ".ctrip.com") || host == "ctrip.com") return "DIRECT";
    if (dnsDomainIs(host, ".ct10000.com") || host == "ct10000.com") return "DIRECT";
    if (dnsDomainIs(host, ".csdn.net") || host == "csdn.net") return "DIRECT";
    if (dnsDomainIs(host, ".crsky.com") || host == "crsky.com") return "DIRECT";
    if (dnsDomainIs(host, ".cqtiyu.com") || host == "cqtiyu.com") return "DIRECT";
    if (dnsDomainIs(host, ".cqnews.net") || host == "cqnews.net") return "DIRECT";
    if (dnsDomainIs(host, ".coo8.com") || host == "coo8.com") return "DIRECT";
    if (dnsDomainIs(host, ".comsenz.com") || host == "comsenz.com") return "DIRECT";
    if (dnsDomainIs(host, ".compete.com") || host == "compete.com") return "DIRECT";
    if (dnsDomainIs(host, ".cocoren.com") || host == "cocoren.com") return "DIRECT";
    if (dnsDomainIs(host, ".cnzz.com") || host == "cnzz.com") return "DIRECT";
    if (dnsDomainIs(host, ".cnxad.com") || host == "cnxad.com") return "DIRECT";
    if (dnsDomainIs(host, ".cnwest.com") || host == "cnwest.com") return "DIRECT";
    if (dnsDomainIs(host, ".cntv.net") || host == "cntv.net") return "DIRECT";
    if (dnsDomainIs(host, ".cnmo.com") || host == "cnmo.com") return "DIRECT";
    if (dnsDomainIs(host, ".cnki.net") || host == "cnki.net") return "DIRECT";
    if (dnsDomainIs(host, ".cnhubei.com") || host == "cnhubei.com") return "DIRECT";
    if (dnsDomainIs(host, ".cngba.com") || host == "cngba.com") return "DIRECT";
    if (dnsDomainIs(host, ".cnfol.com") || host == "cnfol.com") return "DIRECT";
    if (dnsDomainIs(host, ".cnepub.com") || host == "cnepub.com") return "DIRECT";
    if (dnsDomainIs(host, ".cncn.com") || host == "cncn.com") return "DIRECT";
    if (dnsDomainIs(host, ".cnblogs.com") || host == "cnblogs.com") return "DIRECT";
    if (dnsDomainIs(host, ".cnbetacdn.com") || host == "cnbetacdn.com") return "DIRECT";
    if (dnsDomainIs(host, ".cnbeta.com") || host == "cnbeta.com") return "DIRECT";
    if (dnsDomainIs(host, ".cn") || host == "cn") return "DIRECT";
    if (dnsDomainIs(host, ".cmbchina.com") || host == "cmbchina.com") return "DIRECT";
    if (dnsDomainIs(host, ".ci123.com") || host == "ci123.com") return "DIRECT";
    if (dnsDomainIs(host, ".chuangelm.com") || host == "chuangelm.com") return "DIRECT";
    if (dnsDomainIs(host, ".chiphell.com") || host == "chiphell.com") return "DIRECT";
    if (dnsDomainIs(host, ".chinaz.com") || host == "chinaz.com") return "DIRECT";
    if (dnsDomainIs(host, ".chinaw3.com") || host == "chinaw3.com") return "DIRECT";
    if (dnsDomainIs(host, ".chinaunix.net") || host == "chinaunix.net") return "DIRECT";
    if (dnsDomainIs(host, ".chinaren.com") || host == "chinaren.com") return "DIRECT";
    if (dnsDomainIs(host, ".chinanews.com") || host == "chinanews.com") return "DIRECT";
    if (dnsDomainIs(host, ".chinamobile.com") || host == "chinamobile.com") return "DIRECT";
    if (dnsDomainIs(host, ".chinahr.com") || host == "chinahr.com") return "DIRECT";
    if (dnsDomainIs(host, ".chinabyte.com") || host == "chinabyte.com") return "DIRECT";
    if (dnsDomainIs(host, ".china.com") || host == "china.com") return "DIRECT";
    if (dnsDomainIs(host, ".chetx.com") || host == "chetx.com") return "DIRECT";
    if (dnsDomainIs(host, ".chdbits.org") || host == "chdbits.org") return "DIRECT";
    if (dnsDomainIs(host, ".changyou.com") || host == "changyou.com") return "DIRECT";
    if (dnsDomainIs(host, ".cdn20.com") || host == "cdn20.com") return "DIRECT";
    if (dnsDomainIs(host, ".cctvcom") || host == "cctvcom") return "DIRECT";
    if (dnsDomainIs(host, ".cctv.com") || host == "cctv.com") return "DIRECT";
    if (dnsDomainIs(host, ".ccidnet.com") || host == "ccidnet.com") return "DIRECT";
    if (dnsDomainIs(host, ".ccb.com") || host == "ccb.com") return "DIRECT";
    if (dnsDomainIs(host, ".caixin.com") || host == "caixin.com") return "DIRECT";
    if (dnsDomainIs(host, ".caing.com") || host == "caing.com") return "DIRECT";
    if (dnsDomainIs(host, ".cache.netease.com") || host == "cache.netease.com") return "DIRECT";
    if (dnsDomainIs(host, ".brothersoft.com") || host == "brothersoft.com") return "DIRECT";
    if (dnsDomainIs(host, ".boosj.com") || host == "boosj.com") return "DIRECT";
    if (dnsDomainIs(host, ".booksky.org") || host == "booksky.org") return "DIRECT";
    if (dnsDomainIs(host, ".bokee.net") || host == "bokee.net") return "DIRECT";
    if (dnsDomainIs(host, ".bluekai.com") || host == "bluekai.com") return "DIRECT";
    if (dnsDomainIs(host, ".blueidea.com") || host == "blueidea.com") return "DIRECT";
    if (dnsDomainIs(host, ".blogchina.com") || host == "blogchina.com") return "DIRECT";
    if (dnsDomainIs(host, ".blogbus.com") || host == "blogbus.com") return "DIRECT";
    if (dnsDomainIs(host, ".blog.163.com") || host == "blog.163.com") return "DIRECT";
    if (dnsDomainIs(host, ".bjbus.com") || host == "bjbus.com") return "DIRECT";
    if (dnsDomainIs(host, ".bitauto.com") || host == "bitauto.com") return "DIRECT";
    if (dnsDomainIs(host, ".bing.com") || host == "bing.com") return "DIRECT";
    if (dnsDomainIs(host, ".bilibili.tv") || host == "bilibili.tv") return "DIRECT";
    if (dnsDomainIs(host, ".betrad.com") || host == "betrad.com") return "DIRECT";
    if (dnsDomainIs(host, ".bestb2b.com") || host == "bestb2b.com") return "DIRECT";
    if (dnsDomainIs(host, ".bendibao.com") || host == "bendibao.com") return "DIRECT";
    if (dnsDomainIs(host, ".bdstatic.com") || host == "bdstatic.com") return "DIRECT";
    if (dnsDomainIs(host, ".bdimg.com") || host == "bdimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".baomihua.com") || host == "baomihua.com") return "DIRECT";
    if (dnsDomainIs(host, ".bankcomm.com") || host == "bankcomm.com") return "DIRECT";
    if (dnsDomainIs(host, ".baixing.com") || host == "baixing.com") return "DIRECT";
    if (dnsDomainIs(host, ".baihe.com") || host == "baihe.com") return "DIRECT";
    if (dnsDomainIs(host, ".baidupcs.com") || host == "baidupcs.com") return "DIRECT";
    if (dnsDomainIs(host, ".baidu.com") || host == "baidu.com") return "DIRECT";
    if (dnsDomainIs(host, ".babytree.com") || host == "babytree.com") return "DIRECT";
    if (dnsDomainIs(host, ".b2b168.com") || host == "b2b168.com") return "DIRECT";
    if (dnsDomainIs(host, ".atpanel.com") || host == "atpanel.com") return "DIRECT";
    if (dnsDomainIs(host, ".atdmt.com") || host == "atdmt.com") return "DIRECT";
    if (dnsDomainIs(host, ".arpg2.com") || host == "arpg2.com") return "DIRECT";
    if (dnsDomainIs(host, ".apple.com") || host == "apple.com") return "DIRECT";
    if (dnsDomainIs(host, ".appinn.com") || host == "appinn.com") return "DIRECT";
    if (dnsDomainIs(host, ".appgame.com") || host == "appgame.com") return "DIRECT";
    if (dnsDomainIs(host, ".aol.com") || host == "aol.com") return "DIRECT";
    if (dnsDomainIs(host, ".anzhi.com") || host == "anzhi.com") return "DIRECT";
    if (dnsDomainIs(host, ".anjuke.com") || host == "anjuke.com") return "DIRECT";
    if (dnsDomainIs(host, ".amazon.com") || host == "amazon.com") return "DIRECT";
    if (dnsDomainIs(host, ".allyes.com") || host == "allyes.com") return "DIRECT";
    if (dnsDomainIs(host, ".aliyun.com") || host == "aliyun.com") return "DIRECT";
    if (dnsDomainIs(host, ".alivv.com") || host == "alivv.com") return "DIRECT";
    if (dnsDomainIs(host, ".alisoft.com") || host == "alisoft.com") return "DIRECT";
    if (dnsDomainIs(host, ".alipayobjects.com") || host == "alipayobjects.com") return "DIRECT";
    if (dnsDomainIs(host, ".alipay.com") || host == "alipay.com") return "DIRECT";
    if (dnsDomainIs(host, ".alimama.com") || host == "alimama.com") return "DIRECT";
    if (dnsDomainIs(host, ".aliimg.com") || host == "aliimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".aliexpress.com") || host == "aliexpress.com") return "DIRECT";
    if (dnsDomainIs(host, ".alicdn.com") || host == "alicdn.com") return "DIRECT";
    if (dnsDomainIs(host, ".alibaba.com") || host == "alibaba.com") return "DIRECT";
    if (dnsDomainIs(host, ".ali213.net") || host == "ali213.net") return "DIRECT";
    if (dnsDomainIs(host, ".aizhan.com") || host == "aizhan.com") return "DIRECT";
    if (dnsDomainIs(host, ".aipai.com") || host == "aipai.com") return "DIRECT";
    if (dnsDomainIs(host, ".aili.com") || host == "aili.com") return "DIRECT";
    if (dnsDomainIs(host, ".aifang.com") || host == "aifang.com") return "DIRECT";
    if (dnsDomainIs(host, ".aibang.com") || host == "aibang.com") return "DIRECT";
    if (dnsDomainIs(host, ".adtechus.com") || host == "adtechus.com") return "DIRECT";
    if (dnsDomainIs(host, ".adsonar.com") || host == "adsonar.com") return "DIRECT";
    if (dnsDomainIs(host, ".adsame.com") || host == "adsame.com") return "DIRECT";
    if (dnsDomainIs(host, ".ads8.com") || host == "ads8.com") return "DIRECT";
    if (dnsDomainIs(host, ".adroll.com") || host == "adroll.com") return "DIRECT";
    if (dnsDomainIs(host, ".adobe.com") || host == "adobe.com") return "DIRECT";
    if (dnsDomainIs(host, ".adnxs.com") || host == "adnxs.com") return "DIRECT";
    if (dnsDomainIs(host, ".admin5.com") || host == "admin5.com") return "DIRECT";
    if (dnsDomainIs(host, ".ad1111.com") || host == "ad1111.com") return "DIRECT";
    if (dnsDomainIs(host, ".acfun.tv") || host == "acfun.tv") return "DIRECT";
    if (dnsDomainIs(host, ".abchina.com") || host == "abchina.com") return "DIRECT";
    if (dnsDomainIs(host, ".abang.com") || host == "abang.com") return "DIRECT";
    if (dnsDomainIs(host, ".a963.com") || host == "a963.com") return "DIRECT";
    if (dnsDomainIs(host, ".a135.net") || host == "a135.net") return "DIRECT";
    if (dnsDomainIs(host, ".99bill.com") || host == "99bill.com") return "DIRECT";
    if (dnsDomainIs(host, ".99114.com") || host == "99114.com") return "DIRECT";
    if (dnsDomainIs(host, ".9787.com") || host == "9787.com") return "DIRECT";
    if (dnsDomainIs(host, ".968tl.com") || host == "968tl.com") return "DIRECT";
    if (dnsDomainIs(host, ".91.com") || host == "91.com") return "DIRECT";
    if (dnsDomainIs(host, ".88db.com") || host == "88db.com") return "DIRECT";
    if (dnsDomainIs(host, ".859652.com") || host == "859652.com") return "DIRECT";
    if (dnsDomainIs(host, ".7k7k.com") || host == "7k7k.com") return "DIRECT";
    if (dnsDomainIs(host, ".7c.com") || host == "7c.com") return "DIRECT";
    if (dnsDomainIs(host, ".778669.com") || host == "778669.com") return "DIRECT";
    if (dnsDomainIs(host, ".777wyx.com") || host == "777wyx.com") return "DIRECT";
    if (dnsDomainIs(host, ".766.com") || host == "766.com") return "DIRECT";
    if (dnsDomainIs(host, ".70e.com") || host == "70e.com") return "DIRECT";
    if (dnsDomainIs(host, ".701sou.com") || host == "701sou.com") return "DIRECT";
    if (dnsDomainIs(host, ".6rooms.com") || host == "6rooms.com") return "DIRECT";
    if (dnsDomainIs(host, ".6dad.com") || host == "6dad.com") return "DIRECT";
    if (dnsDomainIs(host, ".61.com") || host == "61.com") return "DIRECT";
    if (dnsDomainIs(host, ".5d6d.net") || host == "5d6d.net") return "DIRECT";
    if (dnsDomainIs(host, ".5d6d.com") || host == "5d6d.com") return "DIRECT";
    if (dnsDomainIs(host, ".592zn.com") || host == "592zn.com") return "DIRECT";
    if (dnsDomainIs(host, ".591hx.com") || host == "591hx.com") return "DIRECT";
    if (dnsDomainIs(host, ".58.com") || host == "58.com") return "DIRECT";
    if (dnsDomainIs(host, ".56.com") || host == "56.com") return "DIRECT";
    if (dnsDomainIs(host, ".55tuan.com") || host == "55tuan.com") return "DIRECT";
    if (dnsDomainIs(host, ".55bbs.com") || host == "55bbs.com") return "DIRECT";
    if (dnsDomainIs(host, ".53kf.com") || host == "53kf.com") return "DIRECT";
    if (dnsDomainIs(host, ".52tlbb.com") || host == "52tlbb.com") return "DIRECT";
    if (dnsDomainIs(host, ".52pk.net") || host == "52pk.net") return "DIRECT";
    if (dnsDomainIs(host, ".52kmh.com") || host == "52kmh.com") return "DIRECT";
    if (dnsDomainIs(host, ".51yes.com") || host == "51yes.com") return "DIRECT";
    if (dnsDomainIs(host, ".51jobcdn.com") || host == "51jobcdn.com") return "DIRECT";
    if (dnsDomainIs(host, ".51job.com") || host == "51job.com") return "DIRECT";
    if (dnsDomainIs(host, ".51img1.com") || host == "51img1.com") return "DIRECT";
    if (dnsDomainIs(host, ".51fanli.com") || host == "51fanli.com") return "DIRECT";
    if (dnsDomainIs(host, ".51cto.com") || host == "51cto.com") return "DIRECT";
    if (dnsDomainIs(host, ".51buy.com") || host == "51buy.com") return "DIRECT";
    if (dnsDomainIs(host, ".51auto.com") || host == "51auto.com") return "DIRECT";
    if (dnsDomainIs(host, ".5173.com") || host == "5173.com") return "DIRECT";
    if (dnsDomainIs(host, ".51.la") || host == "51.la") return "DIRECT";
    if (dnsDomainIs(host, ".51.com") || host == "51.com") return "DIRECT";
    if (dnsDomainIs(host, ".500wan.com") || host == "500wan.com") return "DIRECT";
    if (dnsDomainIs(host, ".5000pk.com") || host == "5000pk.com") return "DIRECT";
    if (dnsDomainIs(host, ".4738.com") || host == "4738.com") return "DIRECT";
    if (dnsDomainIs(host, ".4399.com") || host == "4399.com") return "DIRECT";
    if (dnsDomainIs(host, ".3dmgame.com") || host == "3dmgame.com") return "DIRECT";
    if (dnsDomainIs(host, ".39.net") || host == "39.net") return "DIRECT";
    if (dnsDomainIs(host, ".37see.com") || host == "37see.com") return "DIRECT";
    if (dnsDomainIs(host, ".36krcnd.com") || host == "36krcnd.com") return "DIRECT";
    if (dnsDomainIs(host, ".36kr.com") || host == "36kr.com") return "DIRECT";
    if (dnsDomainIs(host, ".360tl.com") || host == "360tl.com") return "DIRECT";
    if (dnsDomainIs(host, ".360doc.com") || host == "360doc.com") return "DIRECT";
    if (dnsDomainIs(host, ".360buyimg.com") || host == "360buyimg.com") return "DIRECT";
    if (dnsDomainIs(host, ".360buy.com") || host == "360buy.com") return "DIRECT";
    if (dnsDomainIs(host, ".3366.com") || host == "3366.com") return "DIRECT";
    if (dnsDomainIs(host, ".315che.com") || host == "315che.com") return "DIRECT";
    if (dnsDomainIs(host, ".2mdn.net") || host == "2mdn.net") return "DIRECT";
    if (dnsDomainIs(host, ".2hua.com") || host == "2hua.com") return "DIRECT";
    if (dnsDomainIs(host, ".293.net") || host == "293.net") return "DIRECT";
    if (dnsDomainIs(host, ".28tui.com") || host == "28tui.com") return "DIRECT";
    if (dnsDomainIs(host, ".28.com") || host == "28.com") return "DIRECT";
    if (dnsDomainIs(host, ".265g.com") || host == "265g.com") return "DIRECT";
    if (dnsDomainIs(host, ".265.com") || host == "265.com") return "DIRECT";
    if (dnsDomainIs(host, ".24quan.com") || host == "24quan.com") return "DIRECT";
    if (dnsDomainIs(host, ".2345.com") || host == "2345.com") return "DIRECT";
    if (dnsDomainIs(host, ".21cn.com") || host == "21cn.com") return "DIRECT";
    if (dnsDomainIs(host, ".1uuc.com") || host == "1uuc.com") return "DIRECT";
    if (dnsDomainIs(host, ".1ting.com") || host == "1ting.com") return "DIRECT";
    if (dnsDomainIs(host, ".1o26.com") || host == "1o26.com") return "DIRECT";
    if (dnsDomainIs(host, ".1mall.com") || host == "1mall.com") return "DIRECT";
    if (dnsDomainIs(host, ".19lou.com") || host == "19lou.com") return "DIRECT";
    if (dnsDomainIs(host, ".198game.com") || host == "198game.com") return "DIRECT";
    if (dnsDomainIs(host, ".17u.com") || host == "17u.com") return "DIRECT";
    if (dnsDomainIs(host, ".17kuxun.com") || host == "17kuxun.com") return "DIRECT";
    if (dnsDomainIs(host, ".17cdn.com") || host == "17cdn.com") return "DIRECT";
    if (dnsDomainIs(host, ".178.com") || host == "178.com") return "DIRECT";
    if (dnsDomainIs(host, ".1778.com") || host == "1778.com") return "DIRECT";
    if (dnsDomainIs(host, ".1717388.com") || host == "1717388.com") return "DIRECT";
    if (dnsDomainIs(host, ".17173.com") || host == "17173.com") return "DIRECT";
    if (dnsDomainIs(host, ".163.com") || host == "163.com") return "DIRECT";
    if (dnsDomainIs(host, ".1616.net") || host == "1616.net") return "DIRECT";
    if (dnsDomainIs(host, ".126.net") || host == "126.net") return "DIRECT";
    if (dnsDomainIs(host, ".126.com") || host == "126.com") return "DIRECT";
    if (dnsDomainIs(host, ".123cha.com") || host == "123cha.com") return "DIRECT";
    if (dnsDomainIs(host, ".120ask.com") || host == "120ask.com") return "DIRECT";
    if (dnsDomainIs(host, ".115img.com") || host == "115img.com") return "DIRECT";
    if (dnsDomainIs(host, ".115.com") || host == "115.com") return "DIRECT";
    if (dnsDomainIs(host, ".114la.com") || host == "114la.com") return "DIRECT";
    if (dnsDomainIs(host, ".100ye.com") || host == "100ye.com") return "DIRECT";
    if (dnsDomainIs(host, ".100tjs.com") || host == "100tjs.com") return "DIRECT";
    if (dnsDomainIs(host, ".10010.com") || host == "10010.com") return "DIRECT";
    if (dnsDomainIs(host, ".0x110.com") || host == "0x110.com") return "DIRECT";
    if (dnsDomainIs(host, ".07073.com") || host == "07073.com") return "DIRECT";
    return "PROXY 127.0.0.1:8087";
}
